export * as authApi from './authApi'
export * as adminApi from './adminApi'
export * as catalogApi from './catalogApi'
export * as favoriteApi from './favoriteApi'
export * as partnerApi from './partnerApi'
