CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id UUID NOT NULL,
    venue_id BIGINT NOT NULL,
    calendar_id BIGINT NOT NULL UNIQUE,
    estimated_guests INT NOT NULL,
    total_estimated_cost DECIMAL(12, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bookings_client
        FOREIGN KEY (client_id) REFERENCES users (id),
    CONSTRAINT fk_bookings_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id),
    CONSTRAINT fk_bookings_calendar
        FOREIGN KEY (calendar_id) REFERENCES venue_calendar (id),
    CONSTRAINT chk_bookings_estimated_guests
        CHECK (estimated_guests > 0),
    CONSTRAINT chk_bookings_total_estimated_cost
        CHECK (total_estimated_cost >= 0)
);

CREATE INDEX idx_bookings_client_id ON bookings (client_id);
CREATE INDEX idx_bookings_venue_id ON bookings (venue_id);
