CREATE TABLE contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL UNIQUE,
    contract_number VARCHAR(100) NOT NULL UNIQUE,
    pdf_file_path VARCHAR(255) NOT NULL,
    client_signed BOOLEAN NOT NULL DEFAULT FALSE,
    manager_signed BOOLEAN NOT NULL DEFAULT FALSE,
    signed_at TIMESTAMP NULL,
    CONSTRAINT fk_contracts_booking
        FOREIGN KEY (booking_id) REFERENCES bookings (id)
);
