CREATE TABLE venue_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    cloudinary_public_id VARCHAR(255),
    display_order INT NOT NULL DEFAULT 0,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_venue_images_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE,
    CONSTRAINT chk_venue_images_display_order
        CHECK (display_order >= 0)
);

CREATE INDEX idx_venue_images_venue_id ON venue_images (venue_id);
CREATE INDEX idx_venue_images_venue_order ON venue_images (venue_id, display_order, id);
CREATE UNIQUE INDEX uq_venue_images_single_primary
    ON venue_images (venue_id)
    WHERE is_primary = TRUE;
