CREATE TABLE wedd_chance_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id BIGINT NOT NULL,
    client_id UUID NOT NULL,
    venue_id BIGINT NOT NULL,
    calendar_id BIGINT NOT NULL,
    guest_count INT NOT NULL,
    special_price_per_guest DECIMAL(10, 2) NOT NULL,
    total_estimated_cost DECIMAL(12, 2) NOT NULL,
    message_text TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
    provisional_expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wcb_deal
        FOREIGN KEY (deal_id) REFERENCES wedd_deals (id) ON DELETE CASCADE,
    CONSTRAINT fk_wcb_client
        FOREIGN KEY (client_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_wcb_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE,
    CONSTRAINT fk_wcb_calendar
        FOREIGN KEY (calendar_id) REFERENCES venue_calendar (id) ON DELETE CASCADE,
    CONSTRAINT chk_wcb_guest_count
        CHECK (guest_count > 0),
    CONSTRAINT chk_wcb_special_price
        CHECK (special_price_per_guest >= 0),
    CONSTRAINT chk_wcb_total_estimated_cost
        CHECK (total_estimated_cost >= 0)
);

CREATE INDEX idx_wcb_client_id ON wedd_chance_bookings (client_id);
CREATE INDEX idx_wcb_venue_id ON wedd_chance_bookings (venue_id);
CREATE INDEX idx_wcb_calendar_id ON wedd_chance_bookings (calendar_id);
CREATE INDEX idx_wcb_status ON wedd_chance_bookings (status);
