CREATE TABLE venue_inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id BIGINT NOT NULL,
    contact_email VARCHAR(255) NOT NULL,
    contact_phone VARCHAR(30),
    message_text TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_venue_inquiries_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE
);

CREATE INDEX idx_venue_inquiries_venue_id ON venue_inquiries (venue_id);
CREATE INDEX idx_venue_inquiries_created_at ON venue_inquiries (created_at);
