CREATE TABLE booking_statuses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO booking_statuses (id, status_name) VALUES
    (1, 'AVAILABLE'),
    (2, 'PROVISIONAL'),
    (3, 'CONFIRMED');
