CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE booking_statuses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO roles (id, name) VALUES
    (1, 'GUEST'),
    (2, 'CLIENT'),
    (3, 'MANAGER'),
    (4, 'ADMIN');

INSERT INTO booking_statuses (id, status_name) VALUES
    (1, 'AVAILABLE'),
    (2, 'PROVISIONAL'),
    (3, 'CONFIRMED');

