CREATE TABLE venues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    style VARCHAR(50) NOT NULL,
    capacity_min INT NOT NULL,
    capacity_max INT NOT NULL,
    has_accommodation BOOLEAN NOT NULL DEFAULT FALSE,
    accommodation_places INT NOT NULL DEFAULT 0,
    base_price_per_guest DECIMAL(10, 2) NOT NULL,
    no_corkage_fee BOOLEAN NOT NULL DEFAULT FALSE,
    civil_wedding_garden BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_venues_manager
        FOREIGN KEY (manager_id) REFERENCES users (id),
    CONSTRAINT chk_venues_capacity
        CHECK (capacity_min > 0 AND capacity_max >= capacity_min),
    CONSTRAINT chk_venues_accommodation_places
        CHECK (accommodation_places >= 0),
    CONSTRAINT chk_venues_base_price
        CHECK (base_price_per_guest >= 0)
);

CREATE TABLE venue_addresses (
    venue_id BIGINT PRIMARY KEY,
    street VARCHAR(150) NOT NULL,
    city VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    voivodeship VARCHAR(50) NOT NULL,
    latitude DECIMAL(10, 8) NOT NULL,
    longitude DECIMAL(11, 8) NOT NULL,
    CONSTRAINT fk_venue_addresses_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE,
    CONSTRAINT chk_venue_addresses_latitude
        CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT chk_venue_addresses_longitude
        CHECK (longitude BETWEEN -180 AND 180)
);

CREATE TABLE user_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    venue_id BIGINT NOT NULL,
    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_favorites_user_venue
        UNIQUE (user_id, venue_id),
    CONSTRAINT fk_user_favorites_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_favorites_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE
);

CREATE INDEX idx_venues_manager_id ON venues (manager_id);
CREATE INDEX idx_user_favorites_user_id ON user_favorites (user_id);
CREATE INDEX idx_user_favorites_venue_id ON user_favorites (venue_id);



