CREATE TABLE venues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_id UUID NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    style VARCHAR(50) NOT NULL,
    capacity_min INT NOT NULL,
    capacity_max INT NOT NULL,
    has_accommodation BOOLEAN NOT NULL DEFAULT FALSE,
    accommodation_places INT NOT NULL DEFAULT 0,
    base_price_per_guest DECIMAL(10, 2) NOT NULL,
    no_corkage_fee BOOLEAN NOT NULL DEFAULT FALSE,
    civil_wedding_garden BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_venues_manager
        FOREIGN KEY (manager_id) REFERENCES users (id),
    CONSTRAINT chk_venues_capacity
        CHECK (capacity_min > 0 AND capacity_max >= capacity_min),
    CONSTRAINT chk_venues_accommodation_places
        CHECK (accommodation_places >= 0),
    CONSTRAINT chk_venues_base_price
        CHECK (base_price_per_guest >= 0)
);

CREATE INDEX idx_venues_manager_id ON venues (manager_id);
