CREATE TABLE venue_calendar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id BIGINT NOT NULL,
    event_date DATE NOT NULL,
    status_id INT NOT NULL,
    provisional_expires_at TIMESTAMP NULL,
    CONSTRAINT uq_venue_calendar_venue_date
        UNIQUE (venue_id, event_date),
    CONSTRAINT fk_venue_calendar_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE,
    CONSTRAINT fk_venue_calendar_status
        FOREIGN KEY (status_id) REFERENCES booking_statuses (id)
);

CREATE TABLE wedd_deals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id BIGINT NOT NULL,
    calendar_id BIGINT NOT NULL UNIQUE,
    discount_percentage INT NOT NULL,
    special_price_per_guest DECIMAL(10, 2) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_wedd_deals_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE,
    CONSTRAINT fk_wedd_deals_calendar
        FOREIGN KEY (calendar_id) REFERENCES venue_calendar (id),
    CONSTRAINT chk_wedd_deals_discount_percentage
        CHECK (discount_percentage BETWEEN 0 AND 100),
    CONSTRAINT chk_wedd_deals_special_price
        CHECK (special_price_per_guest >= 0)
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    venue_id BIGINT NOT NULL,
    calendar_id BIGINT NOT NULL UNIQUE,
    estimated_guests INT NOT NULL,
    total_estimated_cost DECIMAL(12, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bookings_client
        FOREIGN KEY (client_id) REFERENCES users (id),
    CONSTRAINT fk_bookings_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id),
    CONSTRAINT fk_bookings_calendar
        FOREIGN KEY (calendar_id) REFERENCES venue_calendar (id),
    CONSTRAINT chk_bookings_estimated_guests
        CHECK (estimated_guests > 0),
    CONSTRAINT chk_bookings_total_estimated_cost
        CHECK (total_estimated_cost >= 0)
);

CREATE INDEX idx_venue_calendar_venue_id ON venue_calendar (venue_id);
CREATE INDEX idx_venue_calendar_status_id ON venue_calendar (status_id);
CREATE INDEX idx_wedd_deals_venue_id ON wedd_deals (venue_id);
CREATE INDEX idx_bookings_client_id ON bookings (client_id);
CREATE INDEX idx_bookings_venue_id ON bookings (venue_id);

