CREATE TABLE contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL UNIQUE,
    contract_number VARCHAR(100) NOT NULL UNIQUE,
    pdf_file_path VARCHAR(255) NOT NULL,
    client_signed BOOLEAN NOT NULL DEFAULT FALSE,
    manager_signed BOOLEAN NOT NULL DEFAULT FALSE,
    signed_at TIMESTAMP NULL,
    CONSTRAINT fk_contracts_booking
        FOREIGN KEY (booking_id) REFERENCES bookings (id)
);

CREATE TABLE guest_diet_logistics (
    booking_id BIGINT PRIMARY KEY,
    menu_standard_count INT NOT NULL DEFAULT 0,
    menu_vegetarian_count INT NOT NULL DEFAULT 0,
    menu_vegan_count INT NOT NULL DEFAULT 0,
    menu_gluten_free_count INT NOT NULL DEFAULT 0,
    allergies_notes TEXT,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_guest_diet_logistics_booking
        FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
    CONSTRAINT chk_guest_diet_logistics_counts
        CHECK (
            menu_standard_count >= 0
            AND menu_vegetarian_count >= 0
            AND menu_vegan_count >= 0
            AND menu_gluten_free_count >= 0
        )
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    message_text TEXT NOT NULL,
    sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_booking
        FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_sender
        FOREIGN KEY (sender_id) REFERENCES users (id)
);

CREATE INDEX idx_messages_booking_id ON messages (booking_id);
CREATE INDEX idx_messages_sender_id ON messages (sender_id);

