CREATE TABLE venue_calendar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id BIGINT NOT NULL,
    event_date DATE NOT NULL,
    status_id INT NOT NULL,
    provisional_expires_at TIMESTAMP NULL,
    CONSTRAINT uq_venue_calendar_venue_date
        UNIQUE (venue_id, event_date),
    CONSTRAINT fk_venue_calendar_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE,
    CONSTRAINT fk_venue_calendar_status
        FOREIGN KEY (status_id) REFERENCES booking_statuses (id)
);

CREATE INDEX idx_venue_calendar_venue_id ON venue_calendar (venue_id);
CREATE INDEX idx_venue_calendar_status_id ON venue_calendar (status_id);
