CREATE TABLE wedd_deals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id BIGINT NOT NULL,
    calendar_id BIGINT NOT NULL UNIQUE,
    discount_percentage INT NOT NULL,
    special_price_per_guest DECIMAL(10, 2) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_wedd_deals_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE,
    CONSTRAINT fk_wedd_deals_calendar
        FOREIGN KEY (calendar_id) REFERENCES venue_calendar (id),
    CONSTRAINT chk_wedd_deals_discount_percentage
        CHECK (discount_percentage BETWEEN 0 AND 100),
    CONSTRAINT chk_wedd_deals_special_price
        CHECK (special_price_per_guest >= 0)
);

CREATE INDEX idx_wedd_deals_venue_id ON wedd_deals (venue_id);
