name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Pozwala uruchomić proces ręcznie z zakładki Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Pobierz kod z repozytorium
      - uses: actions/checkout@v4

      # 2. Ustaw Javę 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Zbuduj backend i uruchom testy
      - name: Build with Maven
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
        run: |
          cd backend
          chmod +x mvnw
          ./mvnw clean package